<Project Sdk="Microsoft.NET.Sdk">
    <ItemGroup>
        <PackageReference Include="CoreWCF.NetNamedPipe" Version="1.9.1" />
        <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.0" />
    </ItemGroup>
    <ItemGroup>
        <ProjectReference
            Include="..\..\..\Shared\PlantDoctor.Contracts\PlantDoctor.Contracts.csproj" />
        <ProjectReference Include="..\PlantMonitor.Core\PlantMonitor.Core.csproj" />
    </ItemGroup>
</Project>