<Project Sdk="Microsoft.NET.Sdk">
    <ItemGroup>
        <PackageReference Include="CoreWCF.NetNamedPipe" Version="1.5.2" />
        <PackageReference Include="CoreWCF.Primitives" Version="1.5.2" />
        <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.0" />
        <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.0" />
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="..\PlantSimulator.Contracts\PlantSimulator.Contracts.csproj" />
        <ProjectReference Include="..\PlantSimulator.Core\PlantSimulator.Core.csproj" />
    </ItemGroup>
</Project>